### ISSUE TITLE
Silk Screen Issue - ETB2 listed under ETB1 pins

### ISSUE THREAD

**Issue by classicdaily** [FOME-Tech/Polygonus#26]
Silk Screen lists ETB2 under ETB1 pins and ETB1 under ETB2 pins.
Also in here should have CR2 and CR1 to VR2 an VR1 to match firmware naming

![Silk Screen Issue](https://github.com/FOME-Tech/Polygonus/assets/127046187/51578fd7-ca6b-4454-980a-1c2af69cc779)

**Comment by OrchardPerformance** [comment]
Thanks Jake. 

ETB has been corrected for future versions and be ok on the 1.5 version. 

CR vs VR, would prefer to fix the firmware on that side and the two pins are now set up like digital input pins to accept a hall sensor 5v as their default. to be VR they need some kind of differential amp on the base board. 
The spare outputs probably also mean a silk screen change.

Will make an issue for that and the renaming of the spare pin outputs.
